//! C-ABI surface for `dart:ffi`.
//!
//! This is the STATELESS slice of the FFI: fixed-size, pure functions (X25519,
//! X3DH composition, Ed25519 verify, hybrid combine). Each writes into a
//! caller-provided 32-byte buffer and returns 0 on success, non-zero on a bad
//! argument, so there is nothing to allocate or free across the boundary — the
//! simplest, safest shape for FFI.
//!
//! The STATEFUL ratchet (`RatchetSession`) needs opaque session handles + a
//! `free` and length-prefixed buffers; that is better generated by
//! `flutter_rust_bridge` than hand-written. It is the remaining FFI work (see
//! rust/README.md), gated on `cargo install cargo-ndk`.
//!
//! Safety: every pointer is null-checked; input slices are read-only and sized
//! by the contract (32-byte keys, caller-supplied msg length). No panics cross
//! the boundary.

use crate::{ed25519_verify, hybrid_combine, x25519_shared, x3dh_initiate};

/// # Safety: `p` must be null or point to at least 32 readable bytes.
unsafe fn arr32(p: *const u8) -> Option<[u8; 32]> {
    if p.is_null() {
        return None;
    }
    let mut a = [0u8; 32];
    a.copy_from_slice(std::slice::from_raw_parts(p, 32));
    Some(a)
}

/// out = X25519(our_seed, their_pub). Returns 0 on success.
///
/// # Safety: `our_seed`/`their_pub` point to 32 bytes; `out` to 32 writable.
#[no_mangle]
pub unsafe extern "C" fn phantom_x25519_shared(
    our_seed: *const u8,
    their_pub: *const u8,
    out: *mut u8,
) -> i32 {
    let (Some(s), Some(p)) = (arr32(our_seed), arr32(their_pub)) else {
        return 1;
    };
    if out.is_null() {
        return 1;
    }
    let secret = x25519_shared(&s, &p);
    std::ptr::copy_nonoverlapping(secret.as_bytes().as_ptr(), out, 32);
    0
}

/// out = X3DH shared secret (Alice/initiator). `their_opk` may be null (no
/// one-time prekey). Returns 0 on success.
///
/// # Safety: the four key pointers are 32 bytes each (`their_opk` null-ok);
/// `out` is 32 writable bytes.
#[no_mangle]
pub unsafe extern "C" fn phantom_x3dh_initiate(
    our_ik_seed: *const u8,
    eph_seed: *const u8,
    their_ik_pub: *const u8,
    their_spk_pub: *const u8,
    their_opk_pub: *const u8, // null → None
    out: *mut u8,
) -> i32 {
    let (Some(ik), Some(eph), Some(tik), Some(tspk)) = (
        arr32(our_ik_seed),
        arr32(eph_seed),
        arr32(their_ik_pub),
        arr32(their_spk_pub),
    ) else {
        return 1;
    };
    if out.is_null() {
        return 1;
    }
    let opk = arr32(their_opk_pub);
    let secret = x3dh_initiate(&ik, &eph, &tik, &tspk, opk.as_ref());
    std::ptr::copy_nonoverlapping(secret.as_bytes().as_ptr(), out, 32);
    0
}

/// out = hybrid_combine(x3dh, kyber). Returns 0 on success.
///
/// # Safety: `x3dh`/`kyber` are 32 bytes; `out` is 32 writable bytes.
#[no_mangle]
pub unsafe extern "C" fn phantom_hybrid_combine(
    x3dh: *const u8,
    kyber: *const u8,
    out: *mut u8,
) -> i32 {
    let (Some(a), Some(b)) = (arr32(x3dh), arr32(kyber)) else {
        return 1;
    };
    if out.is_null() {
        return 1;
    }
    let secret = hybrid_combine(&a, &b);
    std::ptr::copy_nonoverlapping(secret.as_bytes().as_ptr(), out, 32);
    0
}

/// Returns 1 if the Ed25519 signature verifies, 0 otherwise (also 0 on bad
/// args — a non-verifying result, never a panic).
///
/// # Safety: `public` is 32 bytes, `sig` is 64 bytes, `msg` points to
/// `msg_len` readable bytes (may be null iff `msg_len == 0`).
#[no_mangle]
pub unsafe extern "C" fn phantom_ed25519_verify(
    public: *const u8,
    msg: *const u8,
    msg_len: usize,
    sig: *const u8,
) -> i32 {
    let Some(pk) = arr32(public) else { return 0 };
    if sig.is_null() || (msg.is_null() && msg_len != 0) {
        return 0;
    }
    let mut s = [0u8; 64];
    s.copy_from_slice(std::slice::from_raw_parts(sig, 64));
    let m: &[u8] = if msg_len == 0 {
        &[]
    } else {
        std::slice::from_raw_parts(msg, msg_len)
    };
    ed25519_verify(&pk, m, &s) as i32
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ffi_x25519_shared_round_trips_through_c_abi() {
        let our = [0x11u8; 32];
        let their = crate::x25519_public(&[0x22u8; 32]);
        let mut out = [0u8; 32];
        let rc = unsafe { phantom_x25519_shared(our.as_ptr(), their.as_ptr(), out.as_mut_ptr()) };
        assert_eq!(rc, 0);
        // Matches the direct API (and therefore the Dart vector).
        assert_eq!(out, *crate::x25519_shared(&our, &their).as_bytes());
    }

    #[test]
    fn ffi_null_args_are_rejected_not_ub() {
        let mut out = [0u8; 32];
        let rc = unsafe {
            phantom_x25519_shared(std::ptr::null(), std::ptr::null(), out.as_mut_ptr())
        };
        assert_eq!(rc, 1);
        // Ed25519 verify with a null key → 0 (no panic).
        let rc2 = unsafe {
            phantom_ed25519_verify(std::ptr::null(), std::ptr::null(), 0, std::ptr::null())
        };
        assert_eq!(rc2, 0);
    }
}
